# Generated by Django 4.2.1 on 2023-05-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('pno', models.CharField(max_length=50, verbose_name='pno')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('dob', models.CharField(max_length=50, verbose_name='Dob')),
                ('mock', models.CharField(max_length=50, verbose_name='Mock Ratings')),
            ],
        ),
    ]
